# Generated by Django 3.1.6 on 2021-02-06 10:45

import django.core.files.storage
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookupload',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/Users/emilyhuang/Desktop/TextbookPerfect/src/media/my_sell/'), upload_to=payments.models.image_directory_path),
        ),
    ]
