# Generated by Django 3.1.6 on 2021-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_matching_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('impact', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
