# Generated by Django 3.1.6 on 2021-02-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210206_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='identifier',
            field=models.CharField(default='', max_length=500),
        ),
    ]
